name: first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
  - assets/icons/
  - assets/large_icons/


  fonts:
    - family: Prof
      fonts:
        - asset: fonts/prof.ttf

    - family: baby
      fonts:
        - asset: fonts/prof.ttf

    - family: cute
      fonts:
        - asset: fonts/cute.ttf
